modLoader="javafml"
loaderVersion="[43,)"
license="MIT License"
[[mods]]
modId="createskybound"
version="${file.jarVersion}"
displayName="Create: Skybound"
logoFile="examplemod.png"
credits="Art by GenericSkeletonVillan"
authors="attackeight"
description='''
Create: Skybound aims to be a mod that you add to your Create playthrough that transforms the world into a skyblock, but not just grind for everything and also not just get everything for free.
It will work alongside many other Create addons like Aeronautics, Enchantment Industry, and Steam 'n' Rails to provide an enjoyable Create Skyblock Experience.
'''
[[dependencies.createskybound]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.createskybound]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.createskybound]]
    modId="create"
    mandatory=true
    versionRange="[0.5.1.a,0.6)"
    ordering="NONE"
    side="BOTH"
